name: Upgrade

on:
  # GitHub Actions use UTC time, so 20:00 means 4:00 UTC +8 Timezone
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

permissions:
  contents: write
  actions: read
  checks: write

env:
  NODE_ENV: development
  COMMIT_MSG_BODY: ""
  GH_TOKEN: ${{ github.token }}

jobs:
  upgrade:
    name: Upgrade minor/patch version packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Check outdated packages
        run: |
          {
            echo 'COMMIT_MSG_BODY<<EOF'
            npm outdated --json | jq -cr 'to_entries[] | select( .value.current != .value.wanted ) | "- \(.key) \(.value.current) -> \(.value.wanted)" '
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Upgade packages if needed
        if: ${{ env.COMMIT_MSG_BODY != '' }}
        run: npx -y npm-check-updates -p npm -t semver --install never -u

      - name: Sync lockfile if needed
        if: ${{ env.COMMIT_MSG_BODY != '' }}
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm i

      - name: Commit lockfile if needed
        if: ${{ env.COMMIT_MSG_BODY != '' }}
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "$(gh api /users/${{ github.actor }} | jq .email -r)"
          git add package-lock.json
          git add package.json
          git commit -m "fix(deps): update all non-major dependencies" -m "${{ env.COMMIT_MSG_BODY }}" -m "by CI script"
          git push
